/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jack_Gargan
 */
public class NetworkSettings extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public NetworkSettings() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accelField = new javax.swing.JTextField();
        positionField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        velocityField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        statusField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        accelField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        positionField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        velocityField = new javax.swing.JTextField();
        tempField = new javax.swing.JTextField();
        stripeField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HypED – Poddy McPodface");
        setBackground(new java.awt.Color(0, 0, 153));
        setForeground(new java.awt.Color(51, 0, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(29, 16));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        accelField.setEditable(false);
        accelField.setBackground(new java.awt.Color(204, 204, 255));
        accelField.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        accelField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        accelField.setText("1");
        accelField.setFocusable(false);
        jPanel1.add(accelField);
        accelField.setBounds(520, 150, 170, 20);

        positionField.setEditable(false);
        positionField.setBackground(new java.awt.Color(204, 204, 255));
        positionField.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        positionField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        positionField.setText("1");
        positionField.setFocusable(false);
        jPanel1.add(positionField);
        positionField.setBounds(520, 180, 170, 20);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("cm s^-1");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(350, 220, 80, 20);

        velocityField1.setEditable(false);
        velocityField1.setBackground(new java.awt.Color(204, 204, 255));
        velocityField1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        velocityField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        velocityField1.setText("1");
        jPanel2.add(velocityField1);
        velocityField1.setBounds(180, 220, 170, 20);

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("POD STATUS:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(670, 30, 180, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("POD DATA");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 110, 170, 30);

        statusField1.setEditable(false);
        statusField1.setBackground(new java.awt.Color(204, 204, 255));
        statusField1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        statusField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusField1.setText("1");
        jPanel2.add(statusField1);
        statusField1.setBounds(850, 30, 60, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Velocity:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 220, 170, 20);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Acceleration:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 160, 170, 20);

        accelField1.setEditable(false);
        accelField1.setBackground(new java.awt.Color(204, 204, 255));
        accelField1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        accelField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        accelField1.setText("1");
        jPanel2.add(accelField1);
        accelField1.setBounds(180, 160, 170, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Position:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 190, 170, 20);

        positionField1.setEditable(false);
        positionField1.setBackground(new java.awt.Color(204, 204, 255));
        positionField1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        positionField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        positionField1.setText("1");
        jPanel2.add(positionField1);
        positionField1.setBounds(180, 190, 170, 20);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("cm s^-2");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(350, 160, 80, 20);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 255));
        jLabel17.setText("cm");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(350, 190, 30, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        velocityField.setEditable(false);
        velocityField.setBackground(new java.awt.Color(204, 204, 255));
        velocityField.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        velocityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        velocityField.setText("1");
        velocityField.setFocusable(false);
        jPanel1.add(velocityField);
        velocityField.setBounds(520, 210, 170, 20);

        tempField.setEditable(false);
        tempField.setBackground(new java.awt.Color(204, 204, 255));
        tempField.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        tempField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tempField.setText("1");
        tempField.setFocusable(false);
        jPanel1.add(tempField);
        tempField.setBounds(520, 240, 170, 20);

        stripeField.setEditable(false);
        stripeField.setBackground(new java.awt.Color(204, 204, 255));
        stripeField.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        stripeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        stripeField.setText("1");
        stripeField.setFocusable(false);
        jPanel1.add(stripeField);
        stripeField.setBounds(520, 270, 170, 20);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("NETWORK SETTINGS");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(20, 10, 320, 30);

        saveButton.setText("OK");
        jPanel1.add(saveButton);
        saveButton.setBounds(430, 470, 110, 29);

        settingsButton.setText("Cancel");
        jPanel1.add(settingsButton);
        settingsButton.setBounds(430, 490, 110, 29);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Acceleration:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-30, 160, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 370);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accelField;
    private javax.swing.JTextField accelField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField positionField;
    private javax.swing.JTextField positionField1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JTextField statusField1;
    private javax.swing.JTextField stripeField;
    private javax.swing.JTextField tempField;
    private javax.swing.JTextField velocityField;
    private javax.swing.JTextField velocityField1;
    // End of variables declaration//GEN-END:variables
}
